export interface cvDataInt {
    startYYYYMM: number;
    startDate: string;
    endYYYYMM: number;
    endDate: string;
    location: string;
    city: string;
    country: string[];
    title: string;
    category: string;
    company: string;
    description: string[];
    image: string;
    markedCities: any[]; // { name: "city's name", value: [long, lat, sizeOfMarker] }
    zoom: number; // default should be 1.25
    center: number[]; // default should be 0
    slideshow: string[];
}

const date = new Date();
const present = date.getFullYear() * 100 + date.getMonth() + 1;

export const cvData: cvDataInt[] = [
    {
        startYYYYMM: 201910,
        startDate: "Oct 2019",
        endYYYYMM: present,
        endDate: "Present",
        location: "Stockholm, Sweden",
        city: "Stockholm",
        country: ["Sweden"],
        title: "BI Developer",
        category: "Work",
        company: "Radisson Hotel Group",
        description: [
            "• Create business intelligence dashboards using Angular (typescript/HTML/CSS).",
            "• Model data in and maintain MySQL and Clickhouse databases.",
            "• Create new data pipelines from source to dashboard (e.g. source db -> RHG database -> model data -> deliver to front-end).",
            "• Work from Stockholm as part of a remote geographically-distributed team that is based in Brussels.",
            "• Collaborate with many levels and departments within organization.",
        ],
        image: "rhg.png",
        markedCities: [
            {
                name: "Stockholm",
                value: [18.0686, 59.3293, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
    {
        startYYYYMM: 201801,
        startDate: "Jan 2018",
        endYYYYMM: 201910,
        endDate: "Oct 2019",
        location: "Stockholm, Sweden",
        city: "Stockholm",
        country: ["Sweden"],
        title: "Data Analyst",
        category: "Work",
        company: "Radisson Hotel Group",
        description: [
            "• Created internal system status website that monitored and reported data quality to end users using Angular framework for front-end and Express and MySQL for back-end.",
            "• Designed and built Meetings and Events pricing tool used throughout Northern Europe.",
            "• Developed MySQL scripts and maintained MySQL server/data warehouse.",
            "• Worked with stakeholders to create and maintain tools to facilitate revenue management and drive revenues.",
        ],
        image: "rhg.png",
        markedCities: [
            {
                name: "Stockholm",
                value: [18.0686, 59.3293, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
    {
        startYYYYMM: 201705,
        startDate: "Jun 2017",
        endYYYYMM: 201801,
        endDate: "Dec 2017",
        location: "Stockholm, Sweden",
        city: "Stockholm",
        country: ["Sweden"],
        title: "Miscellaneous coursework",
        category: "Education",
        company: "",
        description: [
            "• Introduction to Computer Science Using Python (6.00.1x)",
            "• Computational Thinking and Data Science (6.00.2x).",
            "• Data Science Specialization (9-course set using R).",
            "• Data Analysis for Life Sciences 1-5: R statistics, linear/matrix algebra, high dimensional data analysis, and using Bioconductor for gene analysis.",
        ],
        image: "sto.JPG",
        markedCities: [
            {
                name: "Stockholm",
                value: [18.0686, 59.3293, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
    {
        startYYYYMM: 201507,
        startDate: "Jul 2015",
        endYYYYMM: 201705,
        endDate: "May 2017",
        location: "Iowa City, IA",
        city: "Iowa City",
        country: ["United States"],
        title: "Scoring Supervisor",
        category: "Work",
        company: "Pearson",
        description: [
            "• Analyzed scoring patterns to identify problematic trends and ensure that students received the correct score.",
            "• Supervised work of other scorers.",
        ],
        image: "pearson.png",
        markedCities: [
            {
                name: "Iowa City",
                value: [-91.5302, 41.6611, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
    {
        startYYYYMM: 201412,
        startDate: "Dec 2014",
        endYYYYMM: 201502,
        endDate: "Feb 2015",
        location: "Gronau-Epe, DE",
        city: "Epe",
        country: ["Germany"],
        title: "Temporary Resident",
        category: "Travel",
        company: "",
        description: [""],
        image: "travel.JPG",
        markedCities: [
            {
                name: "Epe",
                value: [7.0289, 52.1841, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: ["g1.jpg", "g3.jpg", "g4.jpg", "g5.jpg", "g6.jpg"],
    },
    {
        startYYYYMM: 201410,
        startDate: "Nov 2014",
        endYYYYMM: 201412,
        endDate: "Dec 2014",
        location: "Thailand and Cambodia",
        city: "",
        country: ["Thailand", "Cambodia"],
        title: "Backpacker",
        category: "Travel",
        company: "",
        description: [""],
        image: "camb.JPG",
        markedCities: [
            { name: "Bangkok", value: [100.5018, 13.7563, 3] },
            { name: "Ayutthaya", value: [100.5877, 14.3692, 3] },
            { name: "Lopburi", value: [100.6534, 14.7995, 3] },
            { name: "Chiang Mai", value: [98.9853, 18.7883, 3] },
            { name: "Doi Inthanon", value: [98.4871, 18.588, 3] },
            { name: "Pai", value: [98.4405, 19.3582, 3] },
            { name: "Chiang Rai", value: [99.8406, 19.9105, 3] },
            { name: "Khao Yai", value: [101.3722, 14.4387, 3] },
            { name: "Krong Siem Reap", value: [103.8564, 13.3633, 3] },
            { name: "Angkor Wat", value: [103.867, 13.4125, 3] },
        ],
        zoom: 9,
        center: [100, 12],
        slideshow: [
            "t7.jpg",
            "t1.JPG",
            "t2.JPG",
            "t3.JPG",
            "t4.JPG",
            "t5.JPG",
            "t6.JPG",
            "t8.JPG",
            "t9.JPG",
        ],
    },
    {
        startYYYYMM: 201409,
        startDate: "Oct 2014",
        endYYYYMM: 201410,
        endDate: "Nov 2014",
        location: "Nepal",
        city: "",
        country: ["Nepal"],
        title: "Backpacker",
        category: "Travel",
        company: "",
        description: [""],
        image: "nepal.JPG",
        markedCities: [
            { name: "Dhulikhel", value: [85.5561, 27.6253, 3] },
            { name: "Kathmandu", value: [85.324, 27.7172, 3] },
            { name: "Pokhara", value: [83.9856, 28.2096, 3] },
            { name: "Pothana", value: [83.8303, 28.3132, 3] },
        ],
        zoom: 13,
        center: [85.324, 27.7172],
        slideshow: ["n1.JPG", "n2.JPG", "n3.JPG", "n4.JPG", "n5.JPG", "n6.JPG"],
    },
    {
        startYYYYMM: 201408,
        startDate: "Sep 2014",
        endYYYYMM: 201409,
        endDate: "Oct 2014",
        location: "Australia",
        city: "",
        country: ["Australia"],
        title: "Backpacker",
        category: "Travel",
        company: "",
        description: [""],
        image: "aus.jpg",
        markedCities: [
            { name: "Adelaide", value: [138.6007, -34.9285, 3] },
            { name: "Melbourne", value: [144.9631, -37.8136, 3] },
            { name: "Sydney", value: [151.2093, -33.8688, 3] },
            { name: "Byron Bay", value: [153.602, -28.6474, 3] },
            { name: "Gold Coast", value: [153.4, -28.0167, 3] },
            { name: "Noosa", value: [152.9677, -26.3645, 3] },
            { name: "Whitsundays", value: [148.1893, -20.3441, 3] },
            { name: "Cairns", value: [145.7781, -16.9186, 3] },
        ],
        zoom: 5,
        center: [133.7751, -25.2744],
        slideshow: ["a1.JPG", "a5.JPG", "a6.JPG", "a7.JPG", "a8.JPG", "a9.JPG"],
    },
    {
        startYYYYMM: 201407,
        startDate: "Aug 2014",
        endYYYYMM: 201408,
        endDate: "Sep 2014",
        location: "New Zealand",
        city: "",
        country: ["New Zealand"],
        title: "Backpacker",
        category: "Travel",
        company: "",
        description: [""],
        image: "nz.JPG",
        markedCities: [
            { name: "Paihia", value: [174.091, -35.2821, 3] },
            { name: "Auckland", value: [174.763336, -36.848461, 3] },
            { name: "Christchurch", value: [172.639847, -43.52565, 3] },
            { name: "Thames", value: [175.5491, -37.1479, 3] },
            { name: "Cathedral Cove", value: [175.79, -36.8277, 3] },
            { name: "Matamata", value: [175.7817, -37.8132, 3] },
            { name: "Hamilton", value: [175.273392, -37.730675, 3] },
            { name: "Waitomo", value: [175.098572, -38.261894, 3] },
            { name: "Rotorua", value: [176.2378, -38.1446, 3] },
            { name: "Taupo", value: [176.070206, -38.685692, 3] },
            { name: "Mount Tongariro", value: [175.6358, -39.1296, 3] },
            { name: "Napier", value: [176.9136, -39.4919, 3] },
            { name: "Wellington", value: [174.777969, -41.276825, 3] },
            { name: "Picton", value: [174.0057, -41.293, 3] },
            { name: "Motueka", value: [173.0112, -41.1101, 3] },
            { name: "Karamea", value: [172.1282, -41.2509, 3] },
            { name: "Westport", value: [171.5928, -41.7669, 3] },
            { name: "Franz Josef Glacier", value: [170.1819, -43.3873, 3] },
            { name: "Wanaka", value: [169.1417, -44.6943, 3] },
            { name: "Queenstown", value: [168.6616, -45.0302, 3] },
            { name: "Milford Sound", value: [167.8974, -44.6414, 3] },
            { name: "Manapouri", value: [167.609, -45.5662, 3] },
            { name: "Invercargill", value: [168.3615, -46.4179, 3] },
            { name: "The Catlins", value: [169.1972, -46.4636, 3] },
            { name: "Dunedin", value: [170.4911, -45.8668, 3] },
            { name: "Lake Tekapo", value: [170.4762, -44.0041, 3] },
            { name: "Kaikoura", value: [173.6795, -42.3997, 3] },
        ],
        zoom: 13,
        center: [174.886, -40.9006],
        slideshow: [
            "nz1.JPG",
            "nz2.JPG",
            "nz3.JPG",
            "nz5.JPG",
            "nz6.JPG",
            "nz7.JPG",
            "nz8.JPG",
            "nz9.JPG",
        ],
    },
    {
        startYYYYMM: 201007,
        startDate: "Jul 2010",
        endYYYYMM: 201407,
        endDate: "Jul 2014",
        location: "Coralville, IA",
        city: "Coralville",
        country: ["United States"],
        title: "Production Scientist II",
        category: "Work",
        company: "Integrated DNA Technologies",
        description: [
            "• Analyzed finished DNA/RNA data to ensure correct product was produced using a variety of analysis tools.",
            "• Troubleshot production issues using Microsoft AX database software in combination with Excel.",
            "• Trained colleagues on all departmental processes.",
        ],
        image: "idt.png",
        markedCities: [
            {
                name: "Coralville",
                value: [-91.5302, 41.6611, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
    {
        startYYYYMM: 200806,
        startDate: "Jun 2008",
        endYYYYMM: 200910,
        endDate: "Oct 2009",
        location: "New York, NY",
        city: "NYC",
        country: ["United States"],
        title: "Lead Analyst",
        category: "Work",
        company: "EMSL Analytical",
        description: [
            "• Analyzed data using proprietary Oracle-based database software to create client reports while meeting short deadlines.",
            "• Trained and supervised co-workers in all aspects of sample preparation, data analysis, and reporting.",
        ],
        image: "emsl.png",
        markedCities: [
            {
                name: "NYC",
                value: [-74.006, 40.7128, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
    {
        startYYYYMM: 200308,
        startDate: "Aug 2003",
        endYYYYMM: 200707,
        endDate: "Jul 2007",
        location: "Iowa City, IA",
        city: "Iowa City",
        country: ["United States"],
        title: "B.S., Biology",
        category: "Education",
        company: "The University of Iowa",
        description: [
            "• Focus on quantitative analysis of ecological systems.",
            "• Experience in writing scientific papers and presenting research.",
            "• Dean's List",
            "",
            "Course highlights: statistics, population genetics & molecular evolution, organic chemistry, phylogenetics, and ecology.",
            "",
            "Publication: Ahmed Moustafa, ..., David Zear, ..., Debashish Bhattacharya. A phylogenomic approach for studying plastid endosymbiosis. Genome Informatics 21: 165-176 (2008) 165. PMID: 19425156.",
        ],
        image: "uiowa.svg",
        markedCities: [
            {
                name: "Iowa City",
                value: [-91.5302, 41.6611, 4],
            },
        ],
        zoom: 1.25,
        center: [0, 0],
        slideshow: [""],
    },
];

export const colorArrays = {
    Work: ["rgba(26, 154, 213, 0.7)", "rgba(125, 172, 194, 0.7)"],
    Education: ["rgba(175, 125, 221, 0.7)", "rgba(137, 43, 226, 0.7)"],
    Travel: ["rgba(255, 165, 0, 0.7)", "rgba(255, 102, 0, 0.7)"],
};
