export interface cvDataInt {
    startYYYYMM: number;
    startDate: string;
    endYYYYMM: number;
    endDate: string;
    location: string;
    city: string;
    country: string[];
    title: string;
    category: string;
    company: string;
    description: string[];
    image: string;
}

const date = new Date();
const present = date.getFullYear() * 100 + date.getMonth() + 1;

export const cvData: cvDataInt[] = [
    {
        startYYYYMM: 201910,
        startDate: "October 2019",
        endYYYYMM: present,
        endDate: "Present",
        location: "Stockholm, Sweden",
        city: "Stockholm",
        country: ["Sweden"],
        title: "BI Revenue Management Developer EMEA",
        category: "Work",
        company: "Radisson Hotel Group",
        description: [""],
        image: "rhg.png",
    },
    {
        startYYYYMM: 201801,
        startDate: "January 2018",
        endYYYYMM: 201910,
        endDate: "October 2019",
        location: "Stockholm, Sweden",
        city: "Stockholm",
        country: ["Sweden"],
        title: "Data Analyst",
        category: "Work",
        company: "Radisson Hotel Group",
        description: [
            "• Created internal system status website that monitored and reported data quality to end users using Angular framework for front-end and Express and MySQL for back-end.",
            "• Designed and built Meetings and Events pricing tool used throughout Northern Europe.",
            "• Developed MySQL scripts and maintained MySQL server/data warehouse.",
            "• Worked with stakeholders to create and maintain tools to facilitate revenue management and drive revenues.",
        ],
        image: "rhg.png",
    },
    {
        startYYYYMM: 201705,
        startDate: "June 2017",
        endYYYYMM: 201801,
        endDate: "December 2017",
        location: "Stockholm, Sweden",
        city: "Stockholm",
        country: ["Sweden"],
        title: "Miscelaneous coursework",
        category: "Education",
        company: "N/A",
        description: [
            "• Introduction to Computer Science Using Python (6.00.1x)",
            "• Computational Thinking and Data Science (6.00.2x).",
            "• Data Science Specialization (9-course set using R).",
            "• Data Analysis for Life Sciences 1-5: R statistics, linear/matrix algebra, high dimensional data analysis, and using Bioconductor for gene analysis.",
        ],
        image: "sto.JPG",
    },
    {
        startYYYYMM: 201507,
        startDate: "July 2015",
        endYYYYMM: 201705,
        endDate: "May 2017",
        location: "Iowa City, IA",
        city: "Iowa City",
        country: ["United States"],
        title: "Scoring Supervisor",
        category: "Work",
        company: "Pearson",
        description: [
            "• Analyzed scoring patterns to identify problematic trends and ensure that students received the correct score.",
            "• Supervised work of other scorers.",
        ],
        image: "pearson.png",
    },
    {
        startYYYYMM: 201412,
        startDate: "December 2014",
        endYYYYMM: 201502,
        endDate: "February 2015",
        location: "Gronau-Epe, DE",
        city: "Epe",
        country: ["Germany"],
        title: "",
        category: "Travel",
        company: "N/A",
        description: ["Spent time in:", "• Munich.", "• Gronau-Epe."],
        image: "travel.JPG",
    },
    {
        startYYYYMM: 201410,
        startDate: "November 2014",
        endYYYYMM: 201412,
        endDate: "December 2014",
        location: "Thailand and Cambodia",
        city: "",
        country: ["Thailand", "Cambodia"],
        title: "Backpacker",
        category: "Travel",
        company: "N/A",
        description: [
            "• Analyzed scoring patterns to identify problematic trends and ensure that students received the correct score.",
            "• Supervised work of other scorers.",
        ],
        image: "camb.JPG",
    },
    {
        startYYYYMM: 201409,
        startDate: "October 2014",
        endYYYYMM: 201410,
        endDate: "October 2014",
        location: "Nepal",
        city: "",
        country: ["Nepal"],
        title: "Backpacker",
        category: "Travel",
        company: "N/A",
        description: [""],
        image: "nepal.JPG",
    },
    {
        startYYYYMM: 201408,
        startDate: "September 2014",
        endYYYYMM: 201409,
        endDate: "September 2014",
        location: "Australia",
        city: "",
        country: ["Australia"],
        title: "Backpacker",
        category: "Travel",
        company: "N/A",
        description: [""],
        image: "aus.jpg",
    },
    {
        startYYYYMM: 201407,
        startDate: "August 2014",
        endYYYYMM: 201408,
        endDate: "August 2014",
        location: "New Zealand",
        city: "",
        country: ["New Zealand"],
        title: "Backpacker",
        category: "Travel",
        company: "N/A",
        description: [""],
        image: "nz.JPG",
    },
    {
        startYYYYMM: 201007,
        startDate: "July 2010",
        endYYYYMM: 201407,
        endDate: "July 2014",
        location: "Coralville, IA",
        city: "Coralville",
        country: ["United States"],
        title: "Production Scientist II",
        category: "Work",
        company: "Integrated DNA Technologies",
        description: [
            "• Analyzed finished DNA/RNA data to ensure correct product was produced using a variety of analysis tools.",
            "• Troubleshot production issues using Microsoft AX database software in combination with Excel.",
            "• Trained colleagues on all departmental processes.",
        ],
        image: "idt.png",
    },
    {
        startYYYYMM: 200806,
        startDate: "June 2008",
        endYYYYMM: 200910,
        endDate: "October 2009",
        location: "New York, NY",
        city: "NYC",
        country: ["United States"],
        title: "Lead Analyst",
        category: "Work",
        company: "EMSL Analytical",
        description: [
            "• Analyzed data using proprietary Oracle-based database software to create client reports meeting short deadlines.",
            "• Trained and supervised co-workers in all aspects of sample preparation, data analysis, and reporting.",
        ],
        image: "emsl.png",
    },
    {
        startYYYYMM: 200308,
        startDate: "August 2003",
        endYYYYMM: 200707,
        endDate: "July 2007",
        location: "Iowa City, IA",
        city: "Iowa City",
        country: ["United States"],
        title: "B.S., Biology, Ecology and Evolutionary Biology",
        category: "Education",
        company: "The University of Iowa",
        description: [
            "• Course highlights: statistics, population genetics & molecular evolution, organic chemistry, phylogenetics, and ecology. Focus on quantitative analysis of ecological systems.",
            "• Experience in writing scientific papers and presenting research.",
            "",
            "Publication: Ahmed Moustafa, CX Chan, Megan Danforth, David Zear, Hiba Ahmed, Nagnath Jadhav, Trevor Savage, Debashish Bhattacharya. A phylogenomic approach for studying plastid endosymbiosis. Genome Informatics 21: 165-176 (2008) 165. PMID: 19425156.",
        ],
        image: "uiowa.svg",
    },
];

export const colorArrays = {
    Work: ["gray", "darkgray"],
    Education: ["rgb(138, 43, 226)", "rgb(138, 43, 226)"],
    Travel: ["orange", "rgb(255, 102, 0)"],
};
